// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXk_DVIIqty0B2hmAR9S7qFkWIIkgdO4A',
    appId: '1:366882408124:web:3fb62a8832d5abaa0672b9',
    messagingSenderId: '366882408124',
    projectId: 'movies-99403',
    authDomain: 'movies-99403.firebaseapp.com',
    storageBucket: 'movies-99403.firebasestorage.app',
    measurementId: 'G-JR7HERCS8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMBS8x_whiINTI_rSVbgMwLYM1CYRf1_U',
    appId: '1:366882408124:android:3dea91ae31dc12f10672b9',
    messagingSenderId: '366882408124',
    projectId: 'movies-99403',
    storageBucket: 'movies-99403.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBISTDhHZ015EEN3Xnwc1_wbi-gcsSrBmo',
    appId: '1:366882408124:ios:439b41c1290856380672b9',
    messagingSenderId: '366882408124',
    projectId: 'movies-99403',
    storageBucket: 'movies-99403.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBISTDhHZ015EEN3Xnwc1_wbi-gcsSrBmo',
    appId: '1:366882408124:ios:439b41c1290856380672b9',
    messagingSenderId: '366882408124',
    projectId: 'movies-99403',
    storageBucket: 'movies-99403.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXk_DVIIqty0B2hmAR9S7qFkWIIkgdO4A',
    appId: '1:366882408124:web:6fb8fca5606b65490672b9',
    messagingSenderId: '366882408124',
    projectId: 'movies-99403',
    authDomain: 'movies-99403.firebaseapp.com',
    storageBucket: 'movies-99403.firebasestorage.app',
    measurementId: 'G-PB2CDZGVX9',
  );
}
